

#if defined(__MAKECINT__) || defined(G__ROOTCINT)

#pragma link C++ function abort;
#pragma link C++ function abs;
#pragma link C++ function acos;
#pragma link C++ function asin;
#pragma link C++ function asctime;
#pragma link C++ function atan;
#pragma link C++ function atan2;
#pragma link C++ function atof;
#pragma link C++ function atoi;
#pragma link C++ function atol;
#pragma link C++ function calloc;
#pragma link C++ function ceil;
#pragma link C++ function clearerr;
#pragma link C++ function clock;
#pragma link C++ function cos;
#pragma link C++ function cosh;
#pragma link C++ function ctime;
#pragma link C++ function difftime;
#pragma link C++ function div;
#pragma link C++ function exp;
#pragma link C++ function fabs;
#pragma link C++ function fclose;
#pragma link C++ function feof;
#pragma link C++ function ferror;
#pragma link C++ function fflush;
#pragma link C++ function fgetc;
//#pragma link C++ function fgetpos;
#pragma link C++ function fgets;
#pragma link C++ function floor;
#pragma link C++ function fmod;
#pragma link C++ function fopen;
#pragma link C++ function fputc;
#pragma link C++ function fputs;
#pragma link C++ function fread;
#pragma link C++ function free;
#pragma link C++ function freopen;
#pragma link C++ function frexp;
#pragma link C++ function fseek;
//#pragma link C++ function fsetpos;
#pragma link C++ function ftell;
#pragma link C++ function fwrite;
#pragma link C++ function getc;
#pragma link C++ function getchar;
#pragma link C++ function getenv;
#pragma link C++ function gets;
#pragma link C++ function gmtime;
#pragma link C++ function isalnum;
#pragma link C++ function isalpha;
#pragma link C++ function iscntrl;
#pragma link C++ function isdigit;
#pragma link C++ function isgraph;
#pragma link C++ function islower;
#pragma link C++ function isprint;
#pragma link C++ function ispunct;
#pragma link C++ function isspace;
#pragma link C++ function isupper;
#pragma link C++ function isxdigit;
#pragma link C++ function labs;
#pragma link C++ function ldexp;
#pragma link C++ function ldiv;
#pragma link C++ function localeconv;
#pragma link C++ function localtime;
#pragma link C++ function log;
#pragma link C++ function log10;
#pragma link C++ function malloc;
#pragma link C++ function mblen;
#pragma link C++ function mbstowcs;
#pragma link C++ function mbtowc;
#pragma link C++ function memchr;
#pragma link C++ function memcmp;
#pragma link C++ function memcpy;
#pragma link C++ function memmove;
#pragma link C++ function memset;
#pragma link C++ function mktime;
#pragma link C++ function modf;
#pragma link C++ function perror;
#pragma link C++ function pow;
#pragma link C++ function putc;
#pragma link C++ function putchar;
#pragma link C++ function puts;
#pragma link C++ function raise;
#pragma link C++ function rand;
#pragma link C++ function realloc;
#pragma link C++ function remove;
#pragma link C++ function rename;
#pragma link C++ function rewind;
#pragma link C++ function setbuf;
 #pragma link C++ function setlocale;
#pragma link C++ function setvbuf;
#pragma link C++ function sin;
#pragma link C++ function sinh;
#pragma link C++ function sqrt;
#pragma link C++ function srand;
#pragma link C++ function strcat;
#pragma link C++ function strchr;
#pragma link C++ function strcmp;
#pragma link C++ function strcoll;
#pragma link C++ function strcpy;
#pragma link C++ function strcspn;
#pragma link C++ function strerror;
#pragma link C++ function strftime;
#pragma link C++ function strlen;
#pragma link C++ function strncat;
#pragma link C++ function strncmp;
#pragma link C++ function strncpy;
#pragma link C++ function strpbrk;
#pragma link C++ function strrchr;
#pragma link C++ function strspn;
#pragma link C++ function strstr;
#pragma link C++ function strtod;
#pragma link C++ function strtok;
#pragma link C++ function strtol;
#pragma link C++ function strtoul;
#pragma link C++ function strxfrm;
#pragma link C++ function system;
#pragma link C++ function tan;
#pragma link C++ function tanh;
#pragma link C++ function time;
#pragma link C++ function tmpfile;
#pragma link C++ function tmpnam;
#pragma link C++ function tolower;
#pragma link C++ function toupper;
#pragma link C++ function ungetc;
#pragma link C++ function wcstombs;
#pragma link C++ function wctomb;
//int fprintf;
//int printf;
//int sprintf;
//int fscanf;
//int scanf;
//int sscanf;
//void exit;
//int atexit;

#endif

