//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
//---------------------------------------------------------------------------
//---------------------------------------------------------------------------
USEUNIT("..\..\main\G__setup.c");
USEUNIT("..\..\src\debug.c");
USEUNIT("..\..\src\Apiif.cxx");
USEUNIT("..\..\src\auxu.c");
USEUNIT("..\..\src\BaseCls.cxx");
USEUNIT("..\..\src\CallFunc.cxx");
USEUNIT("..\..\src\cast.c");
USEUNIT("..\..\src\Class.cxx");
USEUNIT("..\..\src\DataMbr.cxx");
USEUNIT("..\..\src\Api.cxx");
USEUNIT("..\..\src\input.c");
USEUNIT("..\..\src\disp.c");
USEUNIT("..\..\src\dump.c");
USEUNIT("..\..\src\end.c");
USEUNIT("..\..\src\error.c");
USEUNIT("..\..\src\expr.c");
USEUNIT("..\..\src\cbstrm.cpp");
USEUNIT("..\..\src\fread.c");
USEUNIT("..\..\src\func.c");
USEUNIT("..\..\src\g__cfunc.c");
USEUNIT("..\..\src\gcoll.c");
USEUNIT("..\..\src\global1.c");
USEUNIT("..\..\src\global2.c");
USEUNIT("..\..\src\ifunc.c");
USEUNIT("..\..\src\inherit.c");
USEUNIT("..\..\src\init.c");
USEUNIT("..\..\src\decl.c");
USEUNIT("..\..\src\winnt.c");
USEUNIT("..\..\src\loadfile.c");
USEUNIT("..\..\src\macro.c");
USEUNIT("..\..\src\malloc.c");
USEUNIT("..\..\src\Method.cxx");
USEUNIT("..\..\src\MethodAr.cxx");
USEUNIT("..\..\src\new.c");
USEUNIT("..\..\src\newlink.c");
USEUNIT("..\..\src\oldlink.c");
USEUNIT("..\..\src\opr.c");
USEUNIT("..\..\src\parse.c");
USEUNIT("..\..\src\pause.c");
USEUNIT("..\..\src\pcode.c");
USEUNIT("..\..\src\pragma.c");
USEUNIT("..\..\src\quote.c");
USEUNIT("..\..\src\scrupto.c");
USEUNIT("..\..\src\shl.c");
USEUNIT("..\..\src\sizeof.c");
USEUNIT("..\..\src\stdstrct.c");
USEUNIT("..\..\src\struct.c");
USEUNIT("..\..\src\stub.c");
USEUNIT("..\..\src\tmplt.c");
USEUNIT("..\..\src\Token.cxx");
USEUNIT("..\..\src\Type.cxx");
USEUNIT("..\..\src\typedef.c");
USEUNIT("..\..\src\Typedf.cxx");
USEUNIT("..\..\src\val2a.c");
USEUNIT("..\..\src\value.c");
USEUNIT("..\..\src\var.c");
USEUNIT("..\..\src\intrpt.c");
//---------------------------------------------------------------------------
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
    return 1;
}
//---------------------------------------------------------------------------
