/********************************************************************
* G__c_display0.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__c_display0.h/C is only for compilation.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern void G__c_setup_tagtable();
extern void G__c_setup_typetable();
extern void G__c_setup_memvar();
extern void G__c_setup_global();
extern void G__c_setup_func();
extern void G__set_c_environment();


#include "display0.h"

/* STUB derived class for protected member access */
