/****************************************************************
* unistd.h
*****************************************************************/
#ifndef G__UNISTD_H
#define G__UNISTD_H

#pragma include_noerr <systypes.h>

#ifndef G__TESTMAIN

/* NOTE: posix.dl is not generated by default. 
 * Goto $CINTSYSDIR/lib/posix directory and do 'sh setup' if you use UNIX. */
#pragma ifndef G__POSIX_H
#pragma include_noerr "posix.dll"
#pragma endif

#pragma ifdef G__POSIX_H /* G__POSIX_H is defined in posix.dl */
#define G__POSIX_H_PP
#pragma endif

#ifndef __MAKECINT__
#ifndef G__POSIX_H_PP
#pragma message Note: posix.dll is not found. Do 'sh setup' in $CINTSYSDIR/lib/posix directory if you use UNIX.
#endif
#endif

#endif /* G__TESTMAIN */

#endif
