/****************************************************************
* windows.h
*****************************************************************/
#ifndef G__WINDOWS_H
#define G__WINDOWS_H

// #include <platform.h>

/* NOTE: win32api.dll is not generated by default. 
 * Goto %CINTSYSDIR%\lib\win32api directory and do 'setup' 
 * if you use Windows. */
#pragma include_noerr "win32api.dll"

#ifndef __MAKECINT__ /* ignore the error during dictionary generation */

#pragma ifndef G__WINFUNC_H /* G__WINFUNC_H is defined in win32api.dll */
#error win32api.dll is not ready. Run 'setup.bat' in %CINTSYSDIR%\lib\win32api directory if you use WinNT/95.
#pragma endif

#endif

#ifndef __MAkECINT__
// Parameter for SetPriorityClass()
#define ABOVE_NORMAL_PRIORITY_CLASS     0x00008000
#define BELOW_NORMAL_PRIORITY_CLASS     0x00004000
#define HIGH_PRIORITY_CLASS             0x00000080
#define IDLE_PRIORITY_CLASS             0x00000040
#define NORMAL_PRIORITY_CLASS           0x00000020
#define PROCESS_MODE_BACKGROUND_BEGIN   0x00100000
#define PROCESS_MODE_BACKGROUND_END     0x00200000
#define REALTIME_PRIORITY_CLASS         0x00000100
#endif

#endif
